export const allVehicles = [
    {
        id: 1,
        name: "NTORQ 125",
        type: "scooter",
        hourly: "₹79",
        daily: "₹399",
        weekly: "₹2799",
        monthly: "₹11999",
        description: "Perfect city commuter",
        image: "/images/vehicles/scooter_red.png",
    },
    {
        id: 2,
        name: "R15",
        type: "bike",
        hourly: "₹119",
        daily: "₹999",
        weekly: "₹6999",
        monthly: "₹29999",
        description: "Sporty and stylish",
        image: "/images/vehicles/sport_bike_blue.png",
    },
    {
        id: 3,
        name: "Activa",
        type: "scooter",
        hourly: "₹79",
        daily: "₹399",
        weekly: "₹2799",
        monthly: "₹11999",
        description: "Reliable and efficient",
        image: "/images/vehicles/scooter_red.png",
    },
    {
        id: 4,
        name: "MT-15",
        type: "bike",
        hourly: "₹119",
        daily: "₹799",
        weekly: "₹5599",
        monthly: "₹23999",
        description: "Agile and powerful",
        image: "/images/vehicles/sport_bike_black.png",
    },
    {
        id: 5,
        name: "APACHE 160",
        type: "bike",
        hourly: "₹119",
        daily: "₹599",
        weekly: "₹4199",
        monthly: "₹17999",
        description: "Street fighter style",
        image: "/images/vehicles/sport_bike_black.png",
    },
    {
        id: 6,
        name: "NS 200",
        type: "bike",
        hourly: "₹119",
        daily: "₹799",
        weekly: "₹5599",
        monthly: "₹23999",
        description: "Powerful performance",
        image: "/images/vehicles/sport_bike_black.png",
    },
    {
        id: 7,
        name: "KTM 200 Duke",
        type: "bike",
        hourly: "₹119",
        daily: "₹799",
        weekly: "₹5599",
        monthly: "₹23999",
        description: "Premium adventure",
        image: "/images/vehicles/adventure_bike_orange.png",
    },
    {
        id: 8,
        name: "Himalayan",
        type: "bike",
        hourly: "₹119",
        daily: "₹1199",
        weekly: "₹8399",
        monthly: "₹35999",
        description: "Off-road capability",
        image: "/images/vehicles/cruiser_bike_black.png",
    },
    {
        id: 9,
        name: "THUNDERBIRD 350X",
        type: "bike",
        hourly: "₹119",
        daily: "₹999",
        weekly: "₹6999",
        monthly: "₹29999",
        description: "Classic cruiser",
        image: "/images/vehicles/cruiser_bike_black.png",
    },
    {
        id: 10,
        name: "KTM 250 DUKE",
        type: "bike",
        hourly: "₹119",
        daily: "₹999",
        weekly: "₹6999",
        monthly: "₹29999",
        description: "Aggressive styling",
        image: "/images/vehicles/adventure_bike_orange.png",
    },
    {
        id: 11,
        name: "KTM 390 DUKE",
        type: "bike",
        hourly: "₹119",
        daily: "₹1199",
        weekly: "₹8399",
        monthly: "₹35999",
        description: "Premium duke series",
        image: "/images/vehicles/adventure_bike_orange.png",
    },
    {
        id: 12,
        name: "SP SHINE 125",
        type: "scooter",
        hourly: "₹119",
        daily: "₹499",
        weekly: "₹3499",
        monthly: "₹14999",
        description: "Budget friendly",
        image: "/images/vehicles/scooter_red.png",
    },
]
