export const allVehicles = [
    {
        id: 1,
        name: "NTORQ 125",
        type: "scooter",
        hourly: "₹79",
        daily: "₹399",
        weekly: "₹2399",
        monthly: "₹8499",
        description: "Perfect city commuter",
        image: "/images/vehicles/ntorq_125.png",
    },
    {
        id: 2,
        name: "R15",
        type: "bike",
        hourly: "₹119",
        daily: "₹999",
        weekly: "₹5999",
        monthly: "₹19999",
        description: "Sporty and stylish",
        image: "/images/vehicles/r15.png",
    },
    {
        id: 3,
        name: "Activa",
        type: "scooter",
        hourly: "₹79",
        daily: "₹399",
        weekly: "₹2399",
        monthly: "₹8499",
        description: "Reliable and efficient",
        image: "/images/vehicles/activa.png",
    },
    {
        id: 4,
        name: "MT-15",
        type: "bike",
        hourly: "₹119",
        daily: "₹999",
        weekly: "₹4799",
        monthly: "₹18999",
        description: "Agile and powerful",
        image: "/images/vehicles/mt15.png",
    },
    {
        id: 5,
        name: "APACHE 160",
        type: "bike",
        hourly: "₹119",
        daily: "₹599",
        weekly: "₹3699",
        monthly: "₹11999",
        description: "Street fighter style",
        image: "/images/vehicles/apache_160.png",
    },
    {
        id: 6,
        name: "NS 200",
        type: "bike",
        hourly: "₹119",
        daily: "₹799",
        weekly: "₹4799",
        monthly: "₹18999",
        description: "Powerful performance",
        image: "/images/vehicles/ns200.png",
    },
    {
        id: 7,
        name: "KTM 200 Duke",
        type: "bike",
        hourly: "₹119",
        daily: "₹799",
        weekly: "₹4799",
        monthly: "₹18999",
        description: "Premium adventure",
        image: "/images/vehicles/adventure_bike_orange.png",
    },
    {
        id: 8,
        name: "Himalayan",
        type: "bike",
        hourly: "₹119",
        daily: "₹1199",
        weekly: "₹5999",
        monthly: "₹20399",
        description: "Off-road capability",
        image: "/images/vehicles/cruiser_bike_black.png",
    },
    {
        id: 9,
        name: "THUNDERBIRD 350X",
        type: "bike",
        hourly: "₹119",
        daily: "₹999",
        weekly: "₹5999",
        monthly: "₹20399",
        description: "Classic cruiser",
        image: "/images/vehicles/cruiser_bike_black.png",
    },
    {
        id: 10,
        name: "KTM 250 DUKE",
        type: "bike",
        hourly: "₹119",
        daily: "₹999",
        weekly: "₹5999",
        monthly: "₹19999",
        description: "Aggressive styling",
        image: "/images/vehicles/adventure_bike_orange.png",
    },
    {
        id: 11,
        name: "KTM 390 DUKE",
        type: "bike",
        hourly: "₹119",
        daily: "₹1199",
        weekly: "₹5999",
        monthly: "₹20399",
        description: "Premium duke series",
        image: "/images/vehicles/adventure_bike_orange.png",
    },
    {
        id: 12,
        name: "SP SHINE 125",
        type: "bike",
        hourly: "₹119",
        daily: "₹499",
        weekly: "₹2999",
        monthly: "₹11999",
        description: "Budget friendly",
        image: "/images/vehicles/scooter_red.png",
    },
]
