import Header from "../../components/common/Header"
import Footer from "../../components/common/Footer"

export const metadata = {
  title: "Terms & Conditions - ZupRides | Bike & Car Rentals in Ranchi",
  description: "Terms and conditions for using ZupRides bike and car rental services in Ranchi, Jharkhand.",
}

export default function TermsConditions() {
  const containerStyle = {
    maxWidth: "1000px",
    margin: "0 auto",
    padding: "40px 20px",
    color: "#333",
    lineHeight: "1.8",
  }

  const titleStyle = {
    fontSize: "36px",
    fontWeight: "bold",
    color: "#FF5722",
    marginBottom: "20px",
  }

  const subtitleStyle = {
    fontSize: "16px",
    color: "#666",
    marginBottom: "30px",
    fontStyle: "italic",
  }

  const sectionStyle = {
    marginBottom: "30px",
  }

  const sectionTitleStyle = {
    fontSize: "18px",
    fontWeight: "bold",
    color: "#1a1a1a",
    marginBottom: "12px",
  }

  const sectionNumberStyle = {
    fontSize: "18px",
    fontWeight: "bold",
    color: "#1a1a1a",
    marginBottom: "12px",
  }

  const listItemStyle = {
    marginLeft: "20px",
    marginBottom: "8px",
  }

  const companyBoxStyle = {
    backgroundColor: "#f5f5f5",
    border: "1px solid #ddd",
    padding: "20px",
    marginTop: "30px",
    borderRadius: "8px",
  }

  const companyTitleStyle = {
    fontSize: "18px",
    fontWeight: "bold",
    marginBottom: "12px",
    color: "#FF5722",
  }

  const companyItemStyle = {
    marginBottom: "8px",
    fontSize: "14px",
  }

  return (
    <>
      <Header />
      <div style={containerStyle}>
        <h1 style={titleStyle}>Terms and Conditions</h1>
        <p style={subtitleStyle}>
          This document is an electronic record in terms of the Information Technology Act, 2000 and rules thereunder as
          applicable and the amended provisions pertaining to electronic records in various statutes as amended by the
          Information Technology Act, 2000. This electronic record is generated by a computer system and does not
          require any physical or digital signatures.
        </p>

        <div style={sectionStyle}>
          <p>
            This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology
            (Intermediaries Guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy
            and Terms of Use for access or usage of the domain name, including the related mobile site and mobile
            application (hereinafter referred to as the Platform).
          </p>
        </div>

        <div style={sectionStyle}>
          <p>
            The Platform is owned and operated by the Platform Owner (details provided at the end of this document).
          </p>
        </div>

        <div style={sectionStyle}>
          <p>
            Your use of the Platform, its services, and tools are governed by the following terms and conditions (Terms
            of Use) including the applicable policies which are incorporated herein by way of reference. If you transact
            on the Platform, you shall be subject to the policies that are applicable for such transactions. By mere use
            of the Platform, you shall be contracting with the Platform Owner, and these Terms of Use including the
            policies constitute your binding obligations.
          </p>
        </div>

        <div style={sectionStyle}>
          <p>
            Any terms and conditions proposed by you which are in addition to or which conflict with these Terms of Use
            are expressly rejected by the Platform Owner and shall be of no force or effect. These Terms of Use can be
            modified at any time without prior notice. It is your responsibility to periodically review these Terms of
            Use to stay informed of updates.
          </p>
        </div>

        <div style={sectionStyle}>
          <p>
            For the purpose of these Terms of Use, wherever the context so requires, you, your or user shall mean any
            natural or legal person who has agreed to become a user/buyer on the Platform.
          </p>
        </div>

        <div style={sectionStyle}>
          <p style={{ fontWeight: "bold", fontSize: "16px" }}>
            ACCESSING, BROWSING, OR OTHERWISE USING THE PLATFORM INDICATES YOUR AGREEMENT TO ALL THE TERMS AND
            CONDITIONS UNDER THESE TERMS OF USE. PLEASE READ THEM CAREFULLY BEFORE PROCEEDING.
          </p>
        </div>

        <div style={sectionStyle}>
          <h2 style={sectionTitleStyle}>Key Terms</h2>
        </div>

        <div style={sectionStyle}>
          <h3 style={sectionNumberStyle}>1. Eligibility & Registration</h3>
          <p>
            To access and use the Services, you agree to provide true, accurate, and complete information during and
            after registration, and you are responsible for all acts done through the use of your registered account.
          </p>
        </div>

        <div style={sectionStyle}>
          <h3 style={sectionNumberStyle}>2. Accuracy of Information</h3>
          <p>
            Neither we nor any third parties provide any warranty or guarantee as to the accuracy, timeliness,
            performance, completeness, or suitability of the information and materials on this Platform. You acknowledge
            that such information may contain inaccuracies or errors, and we exclude liability for such inaccuracies to
            the fullest extent permitted by law.
          </p>
        </div>

        <div style={sectionStyle}>
          <h3 style={sectionNumberStyle}>3. Use of Services</h3>
          <p>
            Your use of our Services and Platform is solely at your own risk. You must independently assess and ensure
            that the Services meet your requirements.
          </p>
        </div>

        <div style={sectionStyle}>
          <h3 style={sectionNumberStyle}>4. Intellectual Property</h3>
          <p>
            The contents of the Platform (including but not limited to design, layout, graphics, and text) are
            proprietary. You do not acquire any rights to our intellectual property.
          </p>
        </div>

        <div style={sectionStyle}>
          <h3 style={sectionNumberStyle}>5. Prohibited Use</h3>
          <p>
            You agree not to use the Platform or Services for unlawful purposes or in violation of Indian or local laws.
          </p>
        </div>

        <div style={sectionStyle}>
          <h3 style={sectionNumberStyle}>6. Links to Third Parties</h3>
          <p>
            The Platform may contain links to third-party websites. Accessing these will be governed by the terms of use
            and privacy policies of such third parties.
          </p>
        </div>

        <div style={sectionStyle}>
          <h3 style={sectionNumberStyle}>7. Legal Relationship</h3>
          <p>Initiating a transaction constitutes a legally binding contract between you and the Platform Owner.</p>
        </div>

        <div style={sectionStyle}>
          <h3 style={sectionNumberStyle}>8. Indemnity</h3>
          <p>
            You agree to indemnify and hold harmless the Platform Owner, affiliates, and employees against claims,
            damages, or penalties arising out of your breach of these Terms.
          </p>
        </div>

        <div style={sectionStyle}>
          <h3 style={sectionNumberStyle}>9. Limitation of Liability</h3>
          <p>
            In no event will the Platform Owner be liable for indirect, incidental, or consequential damages. Our
            liability shall not exceed the amount paid by you for the Services giving rise to the claim, or INR 100,
            whichever is less.
          </p>
        </div>

        <div style={sectionStyle}>
          <h3 style={sectionNumberStyle}>10. Force Majeure</h3>
          <p>We are not liable for failure to perform obligations due to events beyond our control.</p>
        </div>

        <div style={sectionStyle}>
          <h3 style={sectionNumberStyle}>11. Governing Law & Jurisdiction</h3>
          <p>
            These Terms shall be governed by the laws of India. All disputes shall be subject to the exclusive
            jurisdiction of the courts specified in the Company Details section below.
          </p>
        </div>

        <div style={sectionStyle}>
          <h3 style={sectionNumberStyle}>12. Communication</h3>
          <p>
            All concerns or communications relating to these Terms must be directed to the contact details provided in
            the Company Details section.
          </p>
        </div>

        <div style={companyBoxStyle}>
          <h2 style={companyTitleStyle}>Company Details</h2>
          <div style={companyItemStyle}>
            <strong>Domain Name (Website):</strong> https://www.zuprides.in/
          </div>
          <div style={companyItemStyle}>
            <strong>Company Name (Platform Owner):</strong> AMAN KUMAR
          </div>
          <div style={companyItemStyle}>
            <strong>Registered Office Address:</strong> Amar Chowk, Harihar Toli, Chutia, Ranchi, Jharkhand
          </div>
          <div style={companyItemStyle}>
            <strong>City & State (Jurisdiction):</strong> Ranchi, Jharkhand
          </div>
        </div>
      </div>
      <Footer />
    </>
  )
}
