
import "./globals.css";
import Header from "@/Components/Header";
import Footer from "@/Components/Footer";
import CallIcon from "@mui/icons-material/Call";
import WhatsAppIcon from "@mui/icons-material/WhatsApp";
import InstagramIcon from "@mui/icons-material/Instagram";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />

        {/* Floating Buttons with Square Design */}
        <div className="fixed bottom-4 right-4 flex flex-col items-end gap-2 z-50">
          <a
            href="tel:+919798146740"
            className="bg-blue-600 hover:bg-blue-700 text-white w-10 h-10 flex items-center justify-center rounded-[5px] shadow-md transition"
            title="Call Now"
          >
            <CallIcon fontSize="small" />
          </a>
          <a
            href="https://wa.me/919798146740"
            target="_blank"
            rel="noopener noreferrer"
            className="bg-green-500 hover:bg-green-600 text-white w-10 h-10 flex items-center justify-center rounded-[5px] shadow-md transition"
            title="Chat on WhatsApp"
          >
            <WhatsAppIcon fontSize="small" />
          </a>
          <a
            href="https://instagram.com/zuprides.india"
            target="_blank"
            rel="noopener noreferrer"
            className="bg-pink-600 hover:bg-pink-700 text-white w-10 h-10 flex items-center justify-center rounded-[5px] shadow-md transition"
            title="Visit Instagram"
          >
            <InstagramIcon fontSize="small" />
          </a>
        </div>
      </body>
    </html>
  );
}
